# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3 # or python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # checking for syntax
      - id: check-yaml
      - id: check-toml
      - id: check-json
      # simple formatting
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      # checks for unresolved merge conflicts
      - id: check-merge-conflict
  # sort python imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  # format f strings
  - repo: https://github.com/ikamensh/flynt/
    rev: "0.78"
    hooks:
      - id: flynt
  # format python code
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.6.0
    hooks:
      - id: docformatter
        additional_dependencies:
          - docformatter[tomli]
        args: ["--in-place", "--config", "./pyproject.toml"]
  # format markdown, yaml, json
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        exclude_types: [python, markdown]
        args: ["--print-width", "100"]
  # format java. Seperate from the above for different tab width
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        name: prettier-java
        types: [java]
        additional_dependencies:
          - prettier
          - prettier-plugin-java
        args: ["--tab-width", "4", "--print-width", "100"]
  # lint python code
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4 # maintain at 5.0.4 until eradicate supports v6
    #when flake8-eradicate supports flake8 6.0 change this rev to newest ver
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-eradicate
          - flake8-bugbear
          - flake8-simplify
          - flake8-builtins
          - flake8-comprehensions
          - flake8-use-fstring
          - flake8-docstrings
          - flake8-rst-docstrings
          - flake8-blind-except
          - pep8-naming
          - darglint
  # format and lint markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint-fix
        args: ["--disable", "md013,md034,md033,md036"]
  # check config files
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-gitlab-ci
      - id: check-readthedocs
  # linting for rst files
  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.1.2
    hooks:
      - id: rstcheck
        additional_dependencies:
          - rstcheck[sphinx]
          - rstcheck[toml]
